### ISSUE TITLE
Usage with an empty | null `commit-message.issue.key`

### ISSUE THREAD

**Issue by deuzu** [bvieira/sv4git#13]
Hello,

We are trying to use AngularJS commit format for our different projets and will recommand the use of `sv4git`. To boost adhesion with the new commit format we want to let developers chose the approach to write the commit message. 

Some will use your tool, some will use `commitizen` and others will use git commands (e.g. `git commit -m "subject" - m "body" -m "JIRA-123"`, `git amend`, git commit template or even Github PR squash and merge).

Because we don't want to force the `sv4git` syntax to developers not using it, we configured it with an empty `commit-message.issue.key` but the prompt display and commit message is not as expected (see colon `:`).

The CLI prompt:
```
❯ git sv cmt
type: chore
scope: test
✔ subject: test
body (leave empty to finish): 
: TEST-1
has breaking changes? [y/n]: n
```

...and the resulting commit message:
```
chore(test): test

: TEST-1
```

**Comment by bvieira** [comment]
Hi @deuzu,

Thanks for using sv4git :)

sv4git was developed using [conventional commits specification](https://www.conventionalcommits.org/en/v1.0.0/#specification), it was inspired by angular commit format, but has some differences.

According with footer specification, it must use a key/value format and the key cannot be empty!

> One or more footers MAY be provided one blank line after the body. Each footer MUST consist of a word token, followed by either a `:<space>` or `<space>#` separator, followed by a string value (this is inspired by the [git trailer convention](https://git-scm.com/docs/git-interpret-trailers)).

[Angular conventional commits](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-footer) uses `Fixes #<issue number>`, you could configure sv4git to use something like this:

```yml
issue:
    key: Fixes
    use-hash: true
```

I wouldn't recommend using a footer without a key, because if you add more than one, it would be difficult to identify each.

Yet, you found a bug, because `: TEST-1` footer is invalid, I think that if the issue key is empty, `commit` command should not ask for issue id. Using `issue.key` as prompt label seem weird when you use `Fixes` or `PR Close` on key, so it´s probably better to use fixed string (`issue`) instead.

**Comment by deuzu** [comment]
Hello, @bvieira thanks for the quick response.

> According with footer specification, it must use a key/value format and the key cannot be empty!

Yeah, that makes sense. We were considering a simplier footer of AngularJS commit convention.
To ease integration with existing tools we decided to use `Closes|Fixes|Relates #JIRA-1` as reference and will configure `sv4git` as follow:
```
footer:
    issue:
        key: "Closes"
        key-synonyms:
            - Fixes
            - Relates
        use-hash: true
```
It fit AngularJS commit convention as well as conventional commits specification.

Thanks again :)
