### ISSUE TITLE
Templating for changelog generation

### ISSUE THREAD

**Issue by hypervtechnics** [bvieira/sv4git#40]
Hi,

how feasible would be the usage of go templates to generate a changelog? This would also solve #24.

This is partly a question (as I can understand if this is a very complex change), partly a feature request. I am using your product and really like it 👍🏼  Thank you for this!

**Comment by bvieira** [comment]
Hey, thanks for keep using sv4git :heart: 

Internally it's using go templates, do you mean to be possible to config it inside the repository? something like a file in the repo (eg: `.sv4git/release-notes.tpl`)? Right now, there is 2 templates, one for release notes and another for changelog (https://github.com/bvieira/sv4git/blob/master/sv/formatter.go#L17)

I think this could work, but I need to think about the retrocompatibility, maybe ignore (or return an error) if both file and release-notes config section exists.. The current config should keep working because there is some people that don't want to learn about go template..

**Comment by rbuckland** [comment]
Borrow from `netflix` @go-jira , their technique. 

The config's are built in by default, and if you want to alter them you run 

```
jira export-templates 
# which will write them to ~/.jira.d/templates/.
```

**Comment by hypervtechnics** [comment]
Yes, that's what I meant 👍🏼 Although I think the difference between release notes and changelog should be more elaborated in the README 😉 Anyways I'd make both of the templates configurable by enabling the user to set a path to a custom path. Then all you need to do is explain which objects are available inside the template and the user can adapt it to their specific needs.

Regarding compatibility I'd prefer the usage of the file if it is defined. If it is possible to detect that the user supplied release-notes configuration print also a warning when the file is used. Something like `WARN: You have defined configuration for the release notes generation, but also defined a custom generation template. The template file may behave differently because the release notes configuration gets ignored.`.

For the go template and template generation process in general I'd recommed the good approach mentioned by @rbuckland.

**Comment by bvieira** [comment]
> Borrow from `netflix/go-jira` [@go-jira](https://github.com/go-jira/jira) , their technique.
> 
> The config's are built in by default, and if you want to alter them you run
> 
> ```
> jira export-templates 
> # which will write them to ~/.jira.d/templates/.
> ```

great.. I'm going to check how they do, thanks.. either way, I rather have this templates committed on the repo (something like `.sv4git/templates/changelog-md.tpl`), so every developer (and pipeline) would get the same result instead of getting it from user home and behave different for each developer.. do you think this would be a problem?

I'm just sad that I didn't create this directory when I created the `.sv4git.yml` file.. but that's life :joy:

**Comment by bvieira** [comment]
> Yes, that's what I meant 👍🏼 Although I think the difference between release notes and changelog should be more elaborated in the README wink Anyways I'd make both of the templates configurable by enabling the user to set a path to a custom path. Then all you need to do is explain which objects are available inside the template and the user can adapt it to their specific needs.
> 

Sorry, I know that I need to rewrite the readme to be easier to understand what the cli do (I always leave it for later).. I hope to do it soon.. If you have any others suggestions for the readme, please just let me know..

A release note it's related with a single release (tag), a changelog is a collection of releases (if you look at changelog template you will see that its only looping on an array of release notes).

> Regarding compatibility I'd prefer the usage of the file if it is defined. If it is possible to detect that the user supplied release-notes configuration print also a warning when the file is used. Something like `WARN: You have defined configuration for the release notes generation, but also defined a custom generation template. The template file may behave differently because the release notes configuration gets ignored.`.
> 
Usually I prefer to thrown an error in this situation, so the behavior is explicit, people tend to ignore warnings.. but I'll ask about it again later, first I need to refactor the code to be possible to have more than one template..

**Comment by hypervtechnics** [comment]
This won't be a problem at all. We just should be able to customize the contents of the template :)

For the yaml file you can also add a new hierarchy level on the configuration loading and then prefer .sv4git/config.yaml over sv4git.yaml - and suddenly everything is in the sv4git directory :)

**Comment by hypervtechnics** [comment]
I also will look into the README and provide my suggestions :)

**Comment by bvieira** [comment]
btw, what do you need to change in the template? do I need to add any aditional function to it?

As I said, we have 2 templates:

**changelog**
[]releasenotes

**releasenotes**
```go
type releaseNoteTemplateVariables struct {
	Release         string
	Date            string
	Sections        map[string]ReleaseNoteSection
	Order           []string
	BreakingChanges BreakingChangeSection
}
```

I'm thinking about changing the sections to array and remove the `order` array.. I'm going to add authors as well to be possible to add on the release template a list of contributors..

so it would probably be something like this:

```go
type releaseNoteTemplateVariables struct {
	Release           string
	Date              string
	Sections          []ReleaseNoteSection
	BreakingChanges   BreakingChangeSection
        Authors           []string
}
```
Probably I gonna need to add a function so it's possible to get a single section from the array (with the current template, this function is not needed since its only loop in the sections)..

Hum.. I forgot that the sections are filtered according with the release-notes config, so right now it wont be a problem to have both (template and config), but this could be a problem if you would like to join more than one commit type in the template :thinking:

**Comment by bvieira** [comment]
@hypervtechnics @rbuckland sorry for the delay, I added the support for custom templates on [v2.7.0](https://github.com/bvieira/sv4git/releases/tag/v2.7.0) :rocket: 

Just let me know if you need any other template function! And, if it's possible, tell me how do you pretend to customize the release template :)

Thanks again for using sv4git :heart:

**Comment by hypervtechnics** [comment]
Wow! 🥳 Thank you so much for this 😄 
Also you don't have to apologize for any delay! Thanks for creating and maintaining this ❤️ 

Using custom templating we can things like emojis for certain scopes and/or commit types. But we can also normalize them to realize aliases for scopes e.g. scopes `core`, `c`, `cr` are all listed under `Core` then which makes the changelog more readable.
